<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Zipto\AliyunLogSdk\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Zipto.AliyunLogSdk.ProtoBuf.LogGroup</code>
 */
class LogGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Zipto.AliyunLogSdk.ProtoBuf.Log Logs = 1;</code>
     */
    private $Logs;
    /**
     * reserved fields
     *
     * Generated from protobuf field <code>optional string Reserved = 2;</code>
     */
    protected $Reserved = null;
    /**
     * Generated from protobuf field <code>optional string Topic = 3;</code>
     */
    protected $Topic = null;
    /**
     * Generated from protobuf field <code>optional string Source = 4;</code>
     */
    protected $Source = null;
    /**
     * Generated from protobuf field <code>repeated .Zipto.AliyunLogSdk.ProtoBuf.LogTag LogTags = 6;</code>
     */
    private $LogTags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Zipto\AliyunLogSdk\ProtoBuf\Log>|\Google\Protobuf\Internal\RepeatedField $Logs
     *     @type string $Reserved
     *           reserved fields
     *     @type string $Topic
     *     @type string $Source
     *     @type array<\Zipto\AliyunLogSdk\ProtoBuf\LogTag>|\Google\Protobuf\Internal\RepeatedField $LogTags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Zipto.AliyunLogSdk.ProtoBuf.Log Logs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->Logs;
    }

    /**
     * Generated from protobuf field <code>repeated .Zipto.AliyunLogSdk.ProtoBuf.Log Logs = 1;</code>
     * @param array<\Zipto\AliyunLogSdk\ProtoBuf\Log>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zipto\AliyunLogSdk\ProtoBuf\Log::class);
        $this->Logs = $arr;

        return $this;
    }

    /**
     * reserved fields
     *
     * Generated from protobuf field <code>optional string Reserved = 2;</code>
     * @return string
     */
    public function getReserved()
    {
        return isset($this->Reserved) ? $this->Reserved : '';
    }

    public function hasReserved()
    {
        return isset($this->Reserved);
    }

    public function clearReserved()
    {
        unset($this->Reserved);
    }

    /**
     * reserved fields
     *
     * Generated from protobuf field <code>optional string Reserved = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReserved($var)
    {
        GPBUtil::checkString($var, True);
        $this->Reserved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Topic = 3;</code>
     * @return string
     */
    public function getTopic()
    {
        return isset($this->Topic) ? $this->Topic : '';
    }

    public function hasTopic()
    {
        return isset($this->Topic);
    }

    public function clearTopic()
    {
        unset($this->Topic);
    }

    /**
     * Generated from protobuf field <code>optional string Topic = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->Topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return isset($this->Source) ? $this->Source : '';
    }

    public function hasSource()
    {
        return isset($this->Source);
    }

    public function clearSource()
    {
        unset($this->Source);
    }

    /**
     * Generated from protobuf field <code>optional string Source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->Source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Zipto.AliyunLogSdk.ProtoBuf.LogTag LogTags = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogTags()
    {
        return $this->LogTags;
    }

    /**
     * Generated from protobuf field <code>repeated .Zipto.AliyunLogSdk.ProtoBuf.LogTag LogTags = 6;</code>
     * @param array<\Zipto\AliyunLogSdk\ProtoBuf\LogTag>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zipto\AliyunLogSdk\ProtoBuf\LogTag::class);
        $this->LogTags = $arr;

        return $this;
    }

}

